# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: messages.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'messages.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emessages.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"}\n\nUserInputs\x12\x16\n\x0epopulationSize\x18\x01 \x01(\x05\x12\x15\n\rinfectionRate\x18\x02 \x01(\x01\x12\x13\n\x0bnumInfected\x18\x03 \x01(\x05\x12\x14\n\x0crecoveryRate\x18\x04 \x01(\x01\x12\x15\n\rtimeStepsDays\x18\x05 \x01(\x05\"K\n\tSimInputs\x12\x0e\n\x06length\x18\x01 \x01(\x05\x12\x16\n\x0e\x65pidemicParam1\x18\x02 \x01(\x05\x12\x16\n\x0e\x65pidemicParam2\x18\x03 \x01(\x05\"z\n\x0b\x44\x61ilyResult\x12(\n\x04time\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x16\n\x0enumSusceptible\x18\x02 \x01(\x05\x12\x13\n\x0bnumInfected\x18\x03 \x01(\x05\x12\x14\n\x0cnumRecovered\x18\x04 \x01(\x05\"+\n\nSimResults\x12\x1d\n\x07results\x18\x01 \x03(\x0b\x32\x0c.DailyResultb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messages_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERINPUTS']._serialized_start=51
  _globals['_USERINPUTS']._serialized_end=176
  _globals['_SIMINPUTS']._serialized_start=178
  _globals['_SIMINPUTS']._serialized_end=253
  _globals['_DAILYRESULT']._serialized_start=255
  _globals['_DAILYRESULT']._serialized_end=377
  _globals['_SIMRESULTS']._serialized_start=379
  _globals['_SIMRESULTS']._serialized_end=422
# @@protoc_insertion_point(module_scope)
